default: &default
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1

development:
  <<: *default
  database: addapi_devel

test:
  <<: *default
  database: addapi_test

production:
  <<: *default
  database: addapi
